# Generated by Django 4.2 on 2024-03-31 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0003_alter_userinfo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='passw',
            field=models.CharField(default=0, max_length=128),
            preserve_default=False,
        ),
    ]
