# Generated by Django 4.2 on 2024-03-31 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0004_userinfo_passw'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='membership_id',
            field=models.CharField(default=0, editable=False, max_length=5, unique=True),
            preserve_default=False,
        ),
    ]
