# Generated by Django 4.2 on 2024-03-31 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0006_alter_userinfo_membership_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='membership_id',
        ),
    ]
