# Generated by Django 4.2 on 2024-03-31 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0007_remove_userinfo_membership_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='membership_id',
            field=models.CharField(default='M0001', editable=False, max_length=5, unique=True),
        ),
    ]
